# Generated by Django 3.1.7 on 2021-05-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_edx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='items',
            new_name='item',
        ),
    ]
