# Generated by Django 3.1.7 on 2021-05-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_edx', '0002_auto_20210522_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
