# Generated by Django 3.1.7 on 2021-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_edx', '0003_auto_20210523_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
