# Generated by Django 3.1.7 on 2021-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_edx', '0005_collegesignin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=500)),
                ('branch_name', models.CharField(max_length=500)),
                ('sem', models.IntegerField(max_length=10)),
            ],
        ),
    ]
