# Generated by Django 3.1.7 on 2021-06-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_edx', '0006_branchreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchreg',
            name='division',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='branchreg',
            name='branch_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='branchreg',
            name='college_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='branchreg',
            name='sem',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
